# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesentence',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcesentence',
            name='trips_parse',
            field=models.TextField(default=''),
        ),
    ]
