# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_sourcesentence_word_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedSkeleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skeleton', models.TextField()),
                ('possible_entries', models.TextField(default='')),
                ('surrounding_words', models.TextField(default='')),
                ('skeleton_type', models.CharField(choices=[('a', 'TRIPS Generated'), ('b', 'Manually Selected'), ('c', 'Processed by SkeletonGen')], max_length=1)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.SourceSentence')),
            ],
        ),
    ]
