# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_processedskeleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedskeleton',
            name='trips_parse',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processedskeleton',
            name='skeleton_type',
            field=models.CharField(choices=[('a', 'TRIPS Generated'), ('b', 'Manually Selected'), ('c', 'Processed by SkeletonGen')], default='a', max_length=1),
        ),
    ]
