# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20161221_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skeleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skeleton', models.TextField()),
            ],
        ),
    ]
